name: Build Releases

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set custom commit variable
        id: set_commit_var
        run: |
          COMMIT_VAR=$(git log -1 --pretty=format:'%h')
          echo "COMMIT_VAR=$COMMIT_VAR" >> $GITHUB_ENV
      - name: Print custom commit variable
        run: echo $COMMIT_VAR
    # - name: Checkout
    #   uses: actions/checkout@v3
    # - name: Install Deps
    #   run: |
    #     sudo apt update
    #     sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
    # - name: Build with Buildozer
    #   run: |
    #     pip install --user --upgrade Cython==0.29.33 virtualenv
    #     pip install --user --upgrade buildozer
    #     export PATH=$PATH:~/.local/bin/
    #     buildozer -v android debug
    # - name: Realese
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "bin/*.apk"
    #     tag: v1.1