name: Build APK
# on: [push,pull_request]
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Buildozer
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade Cython==0.29.33 virtualenv
          pip install --user --upgrade buildozer
          python -m pip install --upgrade pip
          export PATH=$PATH:~/.local/bin/
          buildozer -v android debug
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: bin/

# crear receta para compilar c que se ejecuta en kivy en un procesador arm
# test unit