name: Build APK
on: [push,pull_request]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Buildozer
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          buildozer android debug
          pip install --user --upgrade Cython==0.29.33 virtualenv
          pip install --user --upgrade buildozer
          export PATH=$PATH:~/.local/bin/
          buildozer -v android debug
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*.apk
          tag: build
          overwrite: true
          file_glob: true
